spring.application.name=HireReady1
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/bdHireReady
spring.datasource.username=postgres
spring.datasource.password=admin

# JWT
jwt.secret=ClaveSecretaMuyLargaDeAlMenos256BitsParaHS256HireReady2025!
jwt.expiration-ms=86400000

# AWS S3
aws.access-key=TU_AWS_ACCESS_KEY
aws.secret-key=TU_AWS_SECRET_KEY
aws.region=us-east-1
aws.s3.bucket=hireready-profiles

# Gemini AI
gemini.api-key=AIzaSyAf8ZNQXspyrgzXXxZea0dLXu5vQ__oq5gAIzaSyAf8ZNQXspyrgzXXxZea0dLXu5vQ__oq5g
gemini.model=gemini-2.5-flash-lite

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=TU_EMAIL@gmail.com
spring.mail.password=TU_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


app.base-url=http://localhost:8080
